const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let activeGame='';
function show(id){if(id==='shelf'){clearInterval(timer);board=null;piece=null;startWord()}$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active');activeGame=id;if(id==='tetris')draw();window.scrollTo(0,0)}
$$('.game-card').forEach(b=>b.onclick=()=>show(b.dataset.game));$$('.back').forEach(b=>b.onclick=()=>show('shelf'));$('#home').onclick=()=>show('shelf');
const canvas=$('#tetris-board'),ctx=canvas.getContext('2d'),W=10,H=20,S=30,colors=['#7557ff','#ff5b9d','#54d9f4','#ffd85a','#7ccf75','#ff934f','#b57aff'];let board,piece,score,lines,fall,timer;
const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]]];
function newPiece(){let shape=shapes[Math.floor(Math.random()*shapes.length)].map(r=>[...r]);return{x:Math.floor((W-shape[0].length)/2),y:0,s:shape,c:colors[Math.floor(Math.random()*colors.length)]}}
function collide(p=piece){for(let y=0;y<p.s.length;y++)for(let x=0;x<p.s[y].length;x++)if(p.s[y][x]&&(p.x+x<0||p.x+x>=W||p.y+y>=H||(p.y+y>=0&&board[p.y+y][p.x+x])))return true;return false}
function draw(){ctx.fillStyle='#100b20';ctx.fillRect(0,0,300,600);if(!board)return;for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(board[y][x])block(x,y,board[y][x]);else{ctx.strokeStyle='#241b3b';ctx.strokeRect(x*S,y*S,S,S)}}if(piece)for(let y=0;y<piece.s.length;y++)for(let x=0;x<piece.s[y].length;x++)if(piece.s[y][x])block(piece.x+x,piece.y+y,piece.c)}function block(x,y,c){ctx.fillStyle=c;ctx.fillRect(x*S+2,y*S+2,S-4,S-4)}
function startTetris(){board=Array.from({length:H},()=>Array(W).fill(0));piece=newPiece();score=lines=0;clearInterval(timer);timer=setInterval(()=>move(0,1),650);updateTetris();draw()}
function updateTetris(){$('#tetris-score').textContent=score||0;$('#tetris-lines').textContent=lines||0}function merge(){piece.s.forEach((r,y)=>r.forEach((v,x)=>{if(v&&piece.y+y>=0)board[piece.y+y][piece.x+x]=piece.c}));let cleared=0;board=board.filter(r=>{if(r.every(Boolean)){cleared++;return false}return true});while(board.length<H)board.unshift(Array(W).fill(0));if(cleared){lines+=cleared;score+=cleared*100;updateTetris()}piece=newPiece();if(collide()){clearInterval(timer);$('#tetris-score').textContent='Game over'}}function move(x,y){if(!board)return;piece.x+=x;piece.y+=y;if(collide()){piece.x-=x;piece.y-=y;if(y)merge()}draw()}function rotate(){if(!piece)return;let old=piece.s;piece.s=old[0].map((_,i)=>old.map(r=>r[i]).reverse());if(collide())piece.s=old;draw()}
$('#tetris-start').onclick=startTetris;$$('[data-t]').forEach(b=>b.onclick=()=>{if(!board)startTetris();let a=b.dataset.t;if(a==='rotate')rotate();else move(a==='left'?-1:a==='right'?1:0,a==='down'?1:0)});document.addEventListener('keydown',e=>{if(activeGame!=='tetris'||!board)return;let k=e.key;if(['ArrowLeft','ArrowRight','ArrowDown','ArrowUp'].includes(k))e.preventDefault();if(k==='ArrowLeft')move(-1,0);if(k==='ArrowRight')move(1,0);if(k==='ArrowDown')move(0,1);if(k==='ArrowUp')rotate()});
let points=0,clickPower=1,perSecond=0,cost={finger:20,bot:50,factory:200,arcade:750,portal:2500};function updateClicker(){$('#points').textContent=Math.floor(points);$('#per-second').textContent=`+${perSecond} per second`;$$('.upgrade').forEach(b=>{let c=cost[b.dataset.upgrade];b.querySelector('strong').textContent=c;b.disabled=points<c})}$('#pop-button').onclick=()=>{points+=clickPower;updateClicker()};$$('.upgrade').forEach(b=>b.onclick=()=>{let key=b.dataset.upgrade;if(points<cost[key])return;points-=cost[key];if(key==='finger')clickPower++;if(key==='bot')perSecond++;if(key==='factory')perSecond+=5;if(key==='arcade')perSecond+=10;if(key==='portal')perSecond+=20;cost[key]=Math.ceil(cost[key]*1.65);updateClicker()});setInterval(()=>{points+=perSecond;updateClicker()},1000);updateClicker();
const words=['APPLE','BRAIN','CLOUD','DREAM','FLAME','GAMES','HONEY','JUICE','LASER','MAGIC','NIGHT','PARTY','PIXEL','QUEST','ROBOT','SMILE','SPACE','SPARK','TIGER','WATER'],letters='QWERTYUIOPASDFGHJKLZXCVBNM';let answer,row=0,current='',finished=false;function startWord(){answer=words[Math.floor(Math.random()*words.length)];row=0;current='';finished=false;$('#word-message').textContent='Type a five-letter word and press Enter.';$('#word-board').innerHTML=Array.from({length:30},(_,i)=>`<div class="letter" data-cell="${i}"></div>`).join('');$('#keyboard').innerHTML=[...letters].map(l=>`<button class="key" data-key="${l}">${l}</button>`).join('')+'<button class="key enter" data-key="ENTER">ENTER</button><button class="key enter" data-key="BACK">⌫</button>'}function paint(){for(let i=0;i<5;i++)$(`[data-cell="${row*5+i}"]`).textContent=current[i]||''}function key(k){if(finished)return;if(k==='BACK'){current=current.slice(0,-1);paint();return}if(k==='ENTER'){if(current.length!==5){$('#word-message').textContent='Need five letters!';return}guess();return}if(/^[A-Z]$/.test(k)&&current.length<5){current+=k;paint()}}function guess(){let counts={};[...answer].forEach(l=>counts[l]=(counts[l]||0)+1);let states=[];[...current].forEach((l,i)=>{if(l===answer[i]){states[i]='correct';counts[l]--}});[...current].forEach((l,i)=>{if(!states[i]){states[i]=counts[l]?'present':'absent';if(counts[l])counts[l]--}});states.forEach((s,i)=>{$(`[data-cell="${row*5+i}"]`).classList.add(s);let keyBtn=$(`[data-key="${current[i]}"]`);if(keyBtn&&!keyBtn.classList.contains('correct'))keyBtn.className=`key ${s}`});if(current===answer){$('#word-message').textContent='You got it! New word whenever you want.';finished=true}else if(row===5){$('#word-message').textContent=`The word was ${answer}. Try a new one!`;finished=true}else{row++;current=''}}$('#keyboard').onclick=e=>{if(e.target.dataset.key)key(e.target.dataset.key)};document.addEventListener('keydown',e=>{if(activeGame==='wordle'){let k=e.key==='Backspace'?'BACK':e.key==='Enter'?'ENTER':e.key.toUpperCase();if(k==='BACK'||k==='ENTER'||/^[A-Z]$/.test(k))key(k)}});$('#new-word').onclick=startWord;startWord();show('shelf');
